version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - catnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    networks:
      - catnet
    environment:
      - API_URL=http://backend:8000

networks:
  catnet:
    driver: bridge
